apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "unleash.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "unleash.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "unleash.fullname" . }}
    spec:
      containers:
        - name: {{ template "unleash.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}